version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    # Limit of 1 PR to avoid rebase being blocked as we are modifying the PRs
    open-pull-requests-limit: 1
    labels:
      - dependencies
      - npm
