name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version:
          - '14'
          - '16'

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node Version ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: yarn

      - name: Verify Packages
        run: make verify
