name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version:
          - '14'
          - '16'

    env:
      NPM_VERSION: '8.4.1'

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node Version ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
          cache: npm

      - name: Pin npm version
        run: npm i -g npm@$NPM_VERSION

      - name: Verify Packages
        run: make verify
