name: Publish Packages
on:
  push:
    branches:
      - main

concurrency: changeset-publish

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node 14
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: yarn

      - name: Install Dependencies
        run: make install

      - name: Create Publish PR or Publish to NPM
        uses: changesets/action@v1
        with:
          publish: make publish
        env:
          GITHUB_TOKEN: ${{ secrets.GWYDDION_AUTOMATION_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
